Park2FlyAdminApp/Park2FlyAdminApp/Park2FlyAdminApp/Models/Contract.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Park2FlyAdminApp.Models
{
    public class Contract
    {
        public int ID { get; set; }
         
        [DataType(DataType.Date)]
        public DateTime DataStart { get; set; }
        [DataType(DataType.Date)]
        public DateTime DataFinal { get; set; }
        public int Pret { get; set; }
        [Display(Name = "Locatie")]
        [Required()]
        public int LocatieID { get; set; }
        public int ClientID { get; set; }
        public int FirmaID { get; set; }
        [NotMapped]
        public Client client { get; set; }
        [NotMapped]
        [DataType(DataType.Time)]
        public DateTime TimpStart { get; set; }
        [NotMapped]
        [DataType(DataType.Time)]
        public DateTime TimpFinal { get; set; }
        public Contract()
        {
            
        }
    }
    public class ContractDbContext : DbContext
    {
        public DbSet<Contract> Contracte { get; set; }
        public ContractDbContext()
        {
            this.Database.Connection.ConnectionString = System.Configuration.ConfigurationManager.ConnectionStrings["DbContextConnStr"].ConnectionString;
        }

    }
}

Park2FlyAdminApp/Park2FlyAdminApp/Park2FlyAdminApp/Controllers/ContractController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Park2FlyAdminApp.Models;

namespace Park2FlyAdminApp.Controllers
{
    [CheckAuthorization]
    public class ContractController : Controller
    {
        private ContractDbContext dbContract = new ContractDbContext();
        private ClientDbContext dbClient = new ClientDbContext();
        private AdresaDbContext dbAdresa = new AdresaDbContext();
        private FirmaDbContext dbFirma = new FirmaDbContext();
        private MasinaDbContext masinaDb = new MasinaDbContext();

        // GET: Contract
        public ActionResult Index()
        {
          
            return View(dbContract.Contracte.ToList());
        }

        // GET: Contract
        public ActionResult Plecari(string dataFinal)
        {
            DateTime data;
            if (dataFinal!=null && dataFinal != "")
                data = DateTime.Parse(dataFinal);
            else data = DateTime.Now;
            return View(dbContract.Contracte.Where(m => DbFunctions.DiffDays(m.DataFinal, data) == 0).ToList());
        }

        // GET: Contract/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contract contract = dbContract.Contracte.Find(id);
            if (contract == null)
            {
                return HttpNotFound();
            }
            return View(contract);
        }

        // GET: Contract/Create
        Contract c1 = new Contract();
        
        public ActionResult Create()
        {
            Park2FlyAdminApp.Models.ClientDbContext clientDbContext = new ClientDbContext();
            ViewData["listaClienti"] = clientDbContext.Clienti.OrderBy(l => l.NumeClient).ToList();

            Park2FlyAdminApp.Models.LocatieDbContext locatieDbContext = new LocatieDbContext();
            ViewData["listaLocatii"] = locatieDbContext.Locatii.OrderBy(l=>l.Nume).ToList();
            //   c1.DataFinal = DateTime.Now;
            Contract c1 = new Contract();

           // c1.client = dbClient.Clienti.Find(1);
            //c1.ID=102;
            return View(c1);
        }

        // POST: Contract/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ID,DataStart,DataFinal,Pret,LocatieID,ClientID")] Contract contract)
        public ActionResult Create(FormCollection formCollection)
        {
            try
            {

                Contract contract = new Contract();
                Client client = new Client();
                //ClientDbContext clientDbContext = new ClientDbContext();
                //clientDbContext.Clienti.First(c => c.Numar == "");
                #region get formcollection data
                int idClient = formCollection["IDClient"].Length > 0 ? int.Parse(formCollection["IDClient"]) : 0;

                string numeClient = formCollection["NumeClient"];
                string buletin = formCollection["Buletin"];
                string cnp = formCollection["CNP"];
                string email = formCollection["Email"];
                string telefon = formCollection["client.Telefon"];
                string localitate = formCollection["Localitate"];
                string strada = formCollection["Strada"];
                string numar = formCollection["Numar"];
                string bloc = formCollection["Bloc"];
                string scara = formCollection["Scara"];
                int etaj = formCollection["Etaj"].Length > 0 ? int.Parse(formCollection["Etaj"]) : 0;
                int apartament = formCollection["Apartament"].Length > 0 ? int.Parse(formCollection["Apartament"]) : 0;
                string judet = formCollection["Judet"];


                int idFirma = formCollection["IDFirma"].Length > 0 ? int.Parse(formCollection["IDFirma"]) : 0;
                string numeFirma = formCollection["NumeFirma"];
                string cui = formCollection["CUI"];
                string j = formCollection["J"];
                string cont = formCollection["Cont"];
                string localitateF = formCollection["LocalitateF"];
                string stradaF = formCollection["StradaF"];
                string numarF = formCollection["NumarF"];
                string blocF = formCollection["BlocF"];
                string scaraF = formCollection["ScaraF"];
                int etajF = formCollection["EtajF"].Length > 0 ? int.Parse(formCollection["EtajF"]) : 0;
                int apartamentF = formCollection["ApartamentF"].Length > 0 ? int.Parse(formCollection["ApartamentF"]) : 0;
                string judetF = formCollection["JudetF"];



                #endregion
                if (idClient == 0) //client nou, adresa noua
                {
                    Adresa adresa = new Adresa();
                    adresa.Apartament = apartament;
                    adresa.Bloc = bloc;
                    adresa.Etaj = etaj;
                    adresa.Judet = judet;
                    adresa.Localitate = localitate;
                    adresa.Numar = numar;
                    adresa.Scara = scara;
                    adresa.Strada = strada;

                    dbAdresa.Adrese.Add(adresa);
                    dbAdresa.SaveChanges();


                    client.AdresaID = adresa.ID;
                    client.Buletin = buletin;
                    client.CNP = cnp;
                    client.Email = email;
                    client.NumeClient = numeClient;


                    dbClient.Clienti.Add(client);
                    dbClient.SaveChanges();
                    idClient = client.ID;

                }

                contract.ClientID = idClient;
                client = dbClient.Clienti.Find(idClient);
                if (client.Telefon != telefon)
                {
                    client.Telefon = telefon;
                    dbClient.SaveChanges();

                }


                if (numeFirma != "" && idFirma == 0)//firma noua(nexistenta in DB), adresa noua
                {
                    Adresa adresa = new Adresa();
                    adresa.Apartament = apartamentF;
                    adresa.Bloc = blocF;
                    adresa.Etaj = etajF;
                    adresa.Judet = judetF;
                    adresa.Localitate = localitateF;
                    adresa.Numar = numarF;
                    adresa.Scara = scaraF;
                    adresa.Strada = stradaF;

                    dbAdresa.Adrese.Add(adresa);
                    dbAdresa.SaveChanges();

                    Firma firma = new Firma();
                    firma.Cont = cont;
                    firma.CUI = cui;
                    firma.J = j;
                    firma.NumeCompanie = numeFirma;
                    firma.AdresaID = adresa.ID;
                    dbFirma.Firme.Add(firma);
                    dbFirma.SaveChanges();
                    idFirma = firma.ID;
                }

                contract.FirmaID = idFirma;




                contract.DataFinal = DateTime.Parse(formCollection["DataFinal"]);
                contract.DataFinal += TimeSpan.Parse(formCollection["TimpFinal"]);
                contract.DataStart = DateTime.Parse(formCollection["DataStart"]);
                contract.DataStart += TimeSpan.Parse(formCollection["TimpStart"]);
                contract.LocatieID = Int16.Parse(formCollection["LocatieID"]);
                contract.Pret = Int16.Parse(formCollection["Pret"]);



                dbContract.Contracte.Add(contract);
                dbContract.SaveChanges();


                string[] marca = formCollection["marcaMasina"].Split(',');
                string[] model = formCollection["modelMasina"].Split(',');
                string[] numar_ = formCollection["numarMasina"].Split(',');
                for (int i = 0; i < marca.Length; i++)
                {
                    Masina m = new Masina();
                    m.Marca = marca[i];
                    m.Model = model[i];
                    m.NrInmatriculare = numar_[i];
                    m.ContractID = contract.ID;


                    masinaDb.Masini.Add(m);

                }
                masinaDb.SaveChanges();
                return RedirectToAction("Index");

               }
            catch (Exception ex)
            {
                return RedirectToAction(ex.Message);
            }
        }

        // GET: Contract/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contract contract = dbContract.Contracte.Find(id);
            if (contract == null)
            {
                return HttpNotFound();
            }
            return View(contract);
        }

        // POST: Contract/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Data,DataStart,DataFinal,Pret,LocatieID,ClientID")] Contract contract)
        {
            if (ModelState.IsValid)
            {
                dbContract.Entry(contract).State = EntityState.Modified;
                dbContract.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contract);
        }

        // GET: Contract/Delete/5

Park2FlyAdminApp/Park2FlyAdminApp/Park2FlyAdminApp/Controllers/MasinaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Park2FlyAdminApp.Models;

namespace Park2FlyAdminApp.Controllers
{
    [CheckAuthorization]
    public class MasinaController : Controller
    {
        private MasinaDbContext db = new MasinaDbContext();

        // GET: Masina
        public ActionResult Index()
        {
            return View(db.Masini.ToList());
        }
         
        public ActionResult Contract(int? id)
        {

            return View(db.Masini.Where(m => m.ContractID == id).ToList());
        }

        // GET: Masina/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Masina masina = db.Masini.Find(id);
            if (masina == null)
            {
                return HttpNotFound();
            }
            return View(masina);
        }

        // GET: Masina/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Masina/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Marca,Model,NrInmatriculare,Cheie,ContractID")] Masina masina)
        {
            if (ModelState.IsValid)
            {
                db.Masini.Add(masina);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(masina);
        }

        // GET: Masina/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Masina masina = db.Masini.Find(id);
            if (masina == null)
            {
                return HttpNotFound();
            }
            return View(masina);
        }

        // POST: Masina/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Marca,Model,NrInmatriculare,Cheie,ContractID")] Masina masina)
        {
            if (ModelState.IsValid)
            {
                db.Entry(masina).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(masina);
        }

        // GET: Masina/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Masina masina = db.Masini.Find(id);
            if (masina == null)
            {
                return HttpNotFound();
            }
            return View(masina);
        }

        // POST: Masina/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Masina masina = db.Masini.Find(id);
            db.Masini.Remove(masina);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Park2FlyAdminApp/Park2FlyAdminApp/Park2FlyAdminApp/Views/Contract/Create.cshtml
@model Park2FlyAdminApp.Models.Contract

@{
    /**/

    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";

}


<h2>Contract nou</h2>


@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "createForm" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
               <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">



            @Html.LabelFor(model => model.ClientID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-danger" style="display: none;" id="ClientSelectatBut" onclick="stergeClient()">Stergere Client [<span id="ClientSelectat"></span>]</span>
                @Html.ActionLink("Client nou ", "ViewClientNou", "Contract", null, new { @class = "modal-link btn btn-success" })
                @Html.ActionLink("Selectare client ", "ViewSelectareClient", "Contract", null, new { @class = "modal-link btn btn-warning" })
                @if (Model.client != null)
                {
                    @Html.DisplayFor(model => model.client.NumeClient)
                }

            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FirmaID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                  <span class="btn btn-danger" style="display: none;"  id="FirmaSelectataBut" onclick="stergeFirma()">
                Stergere Companie [<span id="FirmaSelectata"></span>]
                  </span>

                @Html.ActionLink("Companie noua ", "ViewFirmaNoua", "Contract", null, new { @class = "modal-link btn btn-success" })
                @Html.ActionLink("Selectare companie ", "ViewSelectFirma", "Contract", null, new { @class = "modal-link btn btn-warning" })

                @*@Html.DropDownList("FirmaID", new SelectList((List<Park2FlyAdminApp.Models.Client>)ViewData["listaClienti"], "ID", "NumeClient"), "Client", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LocatieID, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.client.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.client.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.client.Telefon, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />


        <div class="form-group">
            @Html.LabelFor(model => model.DataStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataStart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataStart, "", new { @class = "text-danger" })
                @Html.EditorFor(model => model.TimpStart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimpStart, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataFinal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataFinal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataFinal, "", new { @class = "text-danger" })
                @Html.EditorFor(model => model.TimpFinal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimpFinal, "", new { @class = "text-danger" })

            </div>
        </div>
        <hr />
        <div class="form-group">

            <label class="control-label col-md-2"> Mașină </label>
            <div class="col-md-10">
                <input type="button" onclick="AddTextBox()" value="Adauga" class="btn btn-default" />
                <div id="divMasini">

                    <div id="masina_entry" class="control-masini-entry">
                        <input name="marcaMasina" class="control-masini" placeholder="Marca" data-val="true" data-val-required="The Marca field is required." />
                        <span class="field-validation-valid text-danger" data-valmsg-for="marcaMasina" data-valmsg-replace="true"></span>

                        <input type="text" name="modelMasina" class="control-masini" placeholder="Model" data-val="true" data-val-required="The Model field is required." />
                        <span class="field-validation-valid text-danger" data-valmsg-for="modelMasina" data-valmsg-replace="true"></span>

                        <input type="text" name="numarMasina" class="control-masini" placeholder="Numar Inmatriculare" data-val="true" data-val-required="The NrIntamatriculare field is required." />
                        <span class="field-validation-valid text-danger" data-valmsg-for="numarMasina" data-valmsg-replace="true"></span>

                        <input type='button' onclick='RemoveTextBox(this)' value='Remove' class='btn btn -default' />
                    </div>
                </div>
            </div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Pret, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-2">
                @Html.EditorFor(model => model.Pret, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pret, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-1">
              
            </div>
            <div class="col-md-7"></div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.LocatieID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocatieID", new SelectList((List<Park2FlyAdminApp.Models.Locatie>)ViewData["listaLocatii"], "ID", "Nume"), "Locatie", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocatieID, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" onclick="frmSbmt()" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    <input type="hidden" id="IDClientH" name="IDClient" />
    <input type="hidden" id="NumeClientH" name="NumeClient" />
    <input type="hidden" id="BuletinH" name="Buletin" />
    <input type="hidden" id="CNPH" name="CNP" />
    <input type="hidden" id="EmailH" name="Email" />
    <input type="hidden" id="TelefonH" name="Telefon" />

    <input type="hidden" id="LocalitateHC" name="Localitate" />
    <input type="hidden" id="StradaHC" name="Strada" />
    <input type="hidden" id="NumarHC" name="Numar" />
    <input type="hidden" id="BlocHC" name="Bloc" />
    <input type="hidden" id="ScaraHC" name="Scara" />
    <input type="hidden" id="EtajHC" name="Etaj" />
    <input type="hidden" id="ApartamentHC" name="Apartament" />
    <input type="hidden" id="JudetHC" name="Judet" />


    <input type="hidden" id="IDFirmaH" name="IDFirma" />
    <input type="hidden" id="NumeFirmaH" name="NumeFirma" />
    <input type="hidden" id="ContH" name="Cont" />
    <input type="hidden" id="JH" name="J" />
    <input type="hidden" id="CUIH" name="CUI" />

    <input type="hidden" id="LocalitateHF" name="LocalitateF" />
    <input type="hidden" id="StradaHF" name="StradaF" />
    <input type="hidden" id="NumarHF" name="NumarF" />
    <input type="hidden" id="BlocHF" name="BlocF" />
    <input type="hidden" id="ScaraHF" name="ScaraF" />
    <input type="hidden" id="EtajHF" name="EtajF" />
    <input type="hidden" id="ApartamentHF" name="ApartamentF" />
    <input type="hidden" id="JudetHF" name="JudetF" />


}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {

    <script type="text/javascript">


        function frmSbmt() {
            var form = $("#createForm");
            form.validate();
            var idClient = document.getElementById("IDClientH").value;
            var numeClient = document.getElementById("NumeClientH").value;
            if (idClient == "" && numeClient == "") alert("Date Client incorecte");
            else if (form.valid()) {
                form.submit();
            }
            else alert("Date Contract incorecte");
        }
        function stergeClient() {

            $('#IDClientH').val("");
            $('#NumeClientH').val("");
            $('#client_Telefon').val("");
            $('#ClientSelectatBut').hide();

        }
        function stergeFirma() {

            $('#IDFirmaH').val("");
            $('#NumeFirmaH').val("");
            $('#FirmaSelectataBut').hide();

        }
        function AddTextBox() {

            var div = document.createElement('DIV');
            var div_masina = document.getElementById("masina_entry");
            //var inpu = document.getElementById("hfield");
            //inpu.innerText = "merge, bre!";

            div.innerHTML = div_masina.innerHTML
            div.className = "control-masini-entry"
            div.id = "masina_entry"
            document.getElementById("divMasini").appendChild(div);

        }

        function DisplayPersoanaFizica() {
            var divPF = document.getElementById("divPF")
            var divPJ = document.getElementById("divPJ")

            divPF.style.display = 'inline'
            divPJ.style.display = 'none'

        }
        function DisplayPersoanaJuridica() {
            var divPF = document.getElementById("divPF")
            var divPJ = document.getElementById("divPJ")

            divPF.style.display = 'none'
            divPJ.style.display = 'inline'

        }
        function RemoveTextBox(div) {
            var divMasini = document.getElementById("divMasini")
            if (divMasini.childElementCount > 1)
                divMasini.removeChild(div.parentNode);

        }

    </script>
    @Scripts.Render("~/bundles/jqueryval")
}

Park2FlyAdminApp/Park2FlyAdminApp/Park2FlyAdminApp/Views/Contract/Delete.cshtml
@model Park2FlyAdminApp.Models.Contract

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Sigur doriti sa stergeti contractul?</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
}
 

Park2FlyAdminApp/Park2FlyAdminApp/Park2FlyAdminApp/Views/Contract/Details.cshtml
@model Park2FlyAdminApp.Models.Contract

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Contract</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.DataStart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataFinal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pret)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pret)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocatieID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocatieID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientID)
        </dd>

    </dl>
</div>
<p> 
    @Html.ActionLink("Back to List", "Index")
</p>

Park2FlyAdminApp/Park2FlyAdminApp/Park2FlyAdminApp/Views/Contract/Index.cshtml
@model IEnumerable<Park2FlyAdminApp.Models.Contract>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista contracte</h2>

<p>
    @Html.ActionLink("Adauga contract nou", "Create")
</p>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.DataStart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataFinal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pret)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LocatieID)
        </th>

        <th>
            Client
        </th>
        <th>
            Companie
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>

        <td>
            @item.DataStart
        </td>
        <td>

            @item.DataFinal
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pret)
        </td>
        <td>
            @CustomHelpers.DisplayHelper.DisplayLocatie(item.LocatieID)
        </td>
        <td>
            @CustomHelpers.DisplayHelper.DisplayClient(item.ClientID)
        </td>
        <td>
            @CustomHelpers.DisplayHelper.DisplayFirma(item.FirmaID)
        </td>
        <td>  @Html.ActionLink("Lista masini", "Contract", "Masina", new { id = item.ID }, null) </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id = item.ID })
        </td>
    </tr>
}

</table>

Park2FlyAdminApp/Park2FlyAdminApp/Park2FlyAdminApp/Views/Contract/Plecari.cshtml
@model IEnumerable<Park2FlyAdminApp.Models.Contract>

@{
    ViewBag.Title = "Plecari";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Plecari</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DataStart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataFinal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pret)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LocatieID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirmaID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
          @item.DataStart
        </td>
        <td>
           @item.DataFinal
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pret)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LocatieID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClientID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirmaID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>